- .travis.yml
- package-lock.json
- package.json
- server/db/models/index.js
- server/db/models/menu.js
- server/db/models/menu_order.js
- server/db/models/order.js
- server/db/models/restaurant.js
- server/db/models/server.js
- server/db/models/user.js
made models, associations, and edits to boilermaker so that our database, nestegg, could be created.
> finishedDbSetup

- databaseSeedScripts/orderSeedScript.js
> Database seed scripts

- client/components/NewQuery.js
- client/components/Summary.js
- client/components/index.js
- client/routes.js
- package-lock.json
- package.json
- server/db/models/menu.js
- server/db/models/server.js
fixed an enum bug that was causing server to crash. Server should work. Made some basic components.
> DBFIXES, basic Components made

- package-lock.json
- package.json
- server/api/index.js
- server/api/servers.js
installed pg, made a servers api route, and made a get request that using pg that displays info from servers table.
> basic pg get request works

- server/api/servers.js
very small fix for step-by-step instructions for PG config in servers route file.
> smalltypofixInPGCONFIG

- databaseSeedScripts/orderSeedScript.js
- script/seed.js
- server/db/models/index.js
- server/db/models/menu.js
- server/db/models/menu_order.js
> updated model definitions, seeding table in progress

- databaseSeedScripts/orderSeedScript.js
> Updated script file

- client/app.js
- client/components/Navbar.js
- client/components/SideBar.js
> Some styling fixed

- client/components/NewQueryWaitersSex.js
- server/api/waiters.js
made backend route to get enum values
> madeRouteToGetEnumValues

- client/components/Home.js
- client/routes.js
- server/api/orders.js
> updated location of summary component

- server/api/orders.js
- server/api/tables.js
> finishedBusinessSummaryQUeries

- client/components/charts/WaitersTipPercent.js
- server/api/tables.js
> Stock queries

- client/app.js
- client/components/Summary.js
- package.json
> A vworking master

- client/components/StockQueryAnalytics.js
- client/components/charts/WaitersTipPercent.js
- client/store/stockQueryReducer.js
- server/api/analytics.js
- server/api/tables.js
> completed tipPercentageChart

- client/components/StockQueryAnalytics.js
- client/components/charts/MenuSalesNumbers.js
- client/store/stockQueryReducer.js
- server/api/analytics.js
confirming menuSalesNumbersChart
> confirming menuSalesNumbersChart

- server/api/analytics.js
> confirmed menuSalesNumbersChart working

- client/components/BusinessAnalytics/AvgRevenuePerGuestVsDOW.js
- client/components/BusinessAnalytics/BusinessAnalyticsPage.js
- client/components/BusinessAnalytics/MenuSalesNumbersVsMenuItems.js
- client/components/BusinessAnalytics/NumberOfOrdersVsHour.js
- client/components/BusinessAnalytics/TipPercentageVsWaiters.js
- client/components/index.js
- client/routes.js
- client/store/businessAnalyticsReducer.js
- server/api/businessAnalytics.js
> restructured Business Analytics

- sqlQueries/FKsOnTable.sql
- sqlQueries/calendar.sql
- sqlQueries/simpleQueriesForCustom.sql
> sqlQueriesFolder

- client/components/Summary/LineGraphRevenue.js
- client/store/summaryReducer.js
- server/api/summary.js
> added total revenue in summary

- client/components/BusinessAnalytics/AvgNumberOfGuestsVsWaiters.js
- client/components/BusinessAnalytics/AvgNumberOfGuestsVsWaitersPerOrder.js
- client/components/BusinessAnalytics/BusinessAnalyticsPage.js
- client/store/businessAnalyticsReducer.js
- server/api/businessAnalytics.js
Working avg # of guests served by waiter within a time frame per order bar graph
> AV avg#of guestsservedby waiter within a time frame per order

- client/components/Summary/DOWAnalysisTable.js
- client/components/Summary/SummaryPage.js
- server/api/summary.js
> completed dow analysis table in summary page

- server/api/summary.js
> finsihedBEforCalendar

- client/components/Summary/PeakTimeGraph.js
- client/components/Summary/RestaurantInfo.js
- client/components/Summary/SummaryPage.js
- client/components/Summary/TotalRevenue.js
- client/store/summaryReducer.js
- server/api/summary.js
> working on Summary Page Style

- client/components/Summary/Calendar/Calendar.js
- client/components/Summary/Calendar/CalendarStats.js
- client/store/businessAnalyticsReducer.js
- server/api/businessAnalytics.js
deleted second pie graph route, minor cleanups, made "today's" revenue date dynamic.
> minor cleanups

- client/components/Summary/LineGraphRevenue.js
> styled revenue graph in summary page

- server/api/summary.js
fixed the multiple waiters problem on the summary page
> fixed multiple waiters issue

- client/components/Sidebar.js
- client/components/SidebarNav.js
- client/components/UserProfile.js
- script/seed.js
- server/api/users.js
- server/db/models/user.js
> Sidebar and userProfile updated

- client/components/BusinessAnalytics/AvgNumberOfGuestsVsWaitersPerOrder.js
- client/components/BusinessAnalytics/AvgRevenuePerGuestVsDOW.js
- client/components/BusinessAnalytics/MenuSalesNumbersVsMenuItemsTopOrBottom5.js
- client/components/BusinessAnalytics/TipPercentageVsWaiters.js
graphs interval functionality fixed. Pie graph is left.
> onlyPieGraphLeft

- client/components/Summary/SummaryPage.js
- public/style.css
> update summary page styling

- client/components/BusinessAnalytics/AvgRevenuePerGuestVsDOW.js
- client/components/BusinessAnalytics/TipPercentageVsWaiters.js
- client/components/Summary/PeakTimeGraph.js
> fixedSomeScaling

- client/components/Summary/LineGraphRevenue.js
- client/components/Summary/PeakTimeGraph.js
> realFixedScaling

- client/components/BusinessAnalytics/AvgNumberOfGuestsVsWaitersPerOrder.js
- client/components/BusinessAnalytics/AvgRevenuePerGuestVsDOW.js
- client/components/BusinessAnalytics/NumberOfOrdersVsHour.js
- client/components/BusinessAnalytics/TipPercentageVsWaiters.js
added new layman titles for graphs
> added new layman titles for graphs

- client/components/Summary/YelpRatingCard.js
- client/store/summaryReducer.js
- package-lock.json
- package.json
> completed yelp rating

- client/components/Sidebar.js
- client/components/SidebarNav.js
- public/style.css
> Summary page styling

- client/components/Summary/PeakTimeGraph.js
- server/api/businessAnalytics.js
- server/api/summary.js
sanitized existing in-use backend.
> A vsanitizing data

- client/components/BusinessAnalytics/MenuSalesNumbersVsMenuItemsTopOrBottom5.js
- client/components/Summary/Calendar/Calendar.js
- client/components/Summary/Calendar/CalendarStats.js
- client/store/businessAnalyticsReducer.js
- package-lock.json
- package.json
User is not allowed to select date in the future. Pie chart works properly.
> Calendar and pie chart are fixed

- server/api/businessAnalytics.js
- server/api/summary.js
added and clauses to queries to make sure it's user specific.
> made queries restaurant specific to user

- client/components/user-home.spec.js
- client/store/user.spec.js
- databaseSeedScripts/orderSeedScript.js
- package-lock.json
- package.json
- script/seed.spec.js
- server/api/users.spec.js
- server/db/models/user.spec.js
4 specs pass when running npm run test
> A vreal b etests

- client/store/customizedQueryReducer.js
> fixed customQueryFunc

- server/api/customizedQuery.js
this structure is now compatible: [
{tableName: 'menus', menuName: ['lobster'], mealType: ['dinner']}
]
> AV "and" clause for custom

- server/api/summary.js
> madeConditionforDatabase

- databaseSeedScripts/orderSeedScript.js
> reducedSeeds

- databaseSeedScripts/orderSeedScript.js
> increasedSeedsAgain

- package-lock.json
- package.json
- server/api/customizedQuery.js
using library for internal structure
> new internal structure with library

- server/api/customizedQuery.js
> working on serializing custom query object

- client/components/CustomizedQuery/CustomizedQuerySelect.js
- client/components/CustomizedQuery/CustomizedQueryWhere.js
- client/store/customizedQueryReducer.js
> updated metadata reducer

- server/api/customizedQuery.js
> easy query working

- client/store/customizedQueryReducer.js
> completed add and remove from custom query functionality

- client/store/customizedQueryReducer.js
> fixed names of action creators and help funcs in custom query

- server/api/customizedQuery.js
simple queries work. Currently debugging a select * with a join table.
> A vverification of be

- client/components/CustomizedQuery/CustomizedQueryTable.js
> custom query in progress

- server/api/customizedQuery.js
The below example works.   
const anExample = [
{
orders: [
{total: {dataType: 'integer', options: ['$lte', 50]}},
{
timeOfPurchase: {
dataType: 'timestamp with time zone',
options: ['week']
}
}
]
}
]
> seemingly working, except for maybe join table

- client/components/CustomizedQuery/CustomizedQuerySelect.js
> Update custom query

- server/api/customizedQuery.js
> debugging for join-null

- client/components/CustomizedQuery/CustomizedQueryWhere.js
- client/store/customizedQueryReducer.js
- server/api/customizedQuery.js
> Commented back in custom query result

- client/components/CustomizedQuery/CheckBoxField.js
- client/components/CustomizedQuery/CustomizedQueryWhere.js
- client/components/CustomizedQuery/IntegersInputField.js
- client/components/CustomizedQuery/TimeFrameField.js
> update options in custom query works

- server/api/customizedQuery.js
> comments and sanitization

- client/components/CustomizedQuery/CustomizedQueryContainer.js
- client/components/CustomizedQuery/TableResults.js
- package-lock.json
- package.json
- public/style.css
> TableResults table ready

- client/components/CustomizedQuery/SubmitQueryButton.js
- client/components/CustomizedQuery/TableResults.js
- client/store/customizedQueryReducer.js
- server/api/customizedQuery.js
- server/api/exampleCode.md
> still connecting fe and be, fixing func

- client/components/BusinessAnalytics/AvgRevenuePerGuestVsDOW.js
- client/components/Summary/LineGraphRevenue.js
> more graph fixes

- client/store/customizedQueryReducer.js
> reducer update

- client/components/CustomizedQuery/CustomizedQuerySelect.js
- client/store/customizedQueryReducer.js
- server/api/customizedQuery.js
> func type is added to custom query

- client/components/CustomizedQuery/CustomizedQueryPage.js
- client/components/CustomizedQuery/CustomizedQuerySelect.js
- client/components/CustomizedQuery/CustomizedQueryTable.js
> join table somewhat working

- client/components/CustomizedQuery/CustomizedQueryPage.js
- client/components/CustomizedQuery/CustomizedQueryTable.js
disabled combine button unless a table is selected. Fixed an issue with the clear button.
> fe_small fixes for joining

- client/components/Summary/LineGraphRevenue.js
- server/api/customizedQuery.js
> small line graph fix

- client/components/BusinessAnalytics/AvgNumberOfGuestsVsWaitersPerOrder.js
- client/components/BusinessAnalytics/MenuSalesNumbersVsMenuItemsTopOrBottom5.js
- client/components/CustomizedQuery/CustomizedQueryPage.js
- client/components/CustomizedQuery/CustomizedQueryTable.js
- client/store/customizedQueryReducer.js
"combine with" and selections for joins tweaked
> Join table fk fix

- client/components/CustomizedQuery/CustomizedQuerySelect.js
- client/components/CustomizedQuery/IntegersInputField.js
- server/api/customizedQuery.js
> added agg func for date in custom query

- client/components/BusinessAnalytics/AvgNumberOfGuestsVsWaitersPerOrder.js
- client/components/BusinessAnalytics/BusinessAnalyticsPage.js
- client/components/BusinessAnalytics/MonthlyRevenueVsLunchVsDinner.js
- client/store/businessAnalyticsReducer.js
- server/api/businessAnalytics.js
> double line graph made

- client/components/BusinessAnalytics/MonthlyRevenueVsLunchVsDinner.js
- sqlQueries/doubleLineGraph.sql
minor tweaks made on double line graph.
> tweaks on double line graph made

- client/components/CustomizedQuery/CustomizedQueryPage.js
submit button now dynamically  appears only when appropriate
> submit button working

- client/components/CustomizedQuery/CustomizedQueryPage.js
submit button should now work as expected
> tweaked submit button

- databaseSeedScripts/orderSeedScript.js
- script/seed.js
- server/api/businessAnalytics.js
- server/api/customizedQuery.js
- server/api/summary.js
- server/db/models/index.js
- server/db/models/menu_order.js
- sqlQueries/calendar.sql
- sqlQueries/doubleLineGraph.sql
- sqlQueries/simpleQueriesForCustom.sql
> menuOrders to menuItemOrders

- server/api/customizedQuery.js
> Fixed becq

- server/api/customizedQuery.js
> added sort

- server/api/customizedQuery.js
> fixed gender option

- client/components/CustomizedQuery/CustomizedQueryPage.js
- client/components/CustomizedQuery/CustomizedQueryTable.js
- unusedFunctions.md
submit button is working better
> submit button is working better

- client/components/BusinessAnalytics/MonthlyRevenueVsLunchVsDinner.js
- server/api/businessAnalytics.js
hard coded fix for double line graph.
> patch fix for double line graph

- client/components/BusinessAnalytics/MonthlyRevenueVsLunchVsDinner.js
- server/api/businessAnalytics.js
- server/api/summary.js
> Saav fe final fixes

- databaseSeedScripts/orderSeedScript.js
> changed counter to 1000

- databaseSeedScripts/orderSeedScript.js
> changed counter to 900

- databaseSeedScripts/orderSeedScript.js
> changed counter to 10000 again

- databaseSeedScripts/orderSeedScript.js
> seeding test
